// <auto-generated />
using System;
using CommerceLab.Modules.Catalogo.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommerceLab.Modules.Catalogo.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(CatalogoDBContext))]
    partial class CatalogoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalogo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommerceLab.Modules.Catalogo.Domain.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_disponivel");

                    b.Property<int>("QuantidadeReservada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_reservada");

                    b.HasKey("Id")
                        .HasName("pk_estoques");

                    b.HasIndex("ProdutoId")
                        .IsUnique()
                        .HasDatabaseName("ix_estoques_produto_id");

                    b.ToTable("estoques", "catalogo");
                });

            modelBuilder.Entity("CommerceLab.Modules.Catalogo.Domain.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("preco");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_produtos");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_produtos_sku");

                    b.ToTable("produtos", "catalogo");
                });

            modelBuilder.Entity("CommerceLab.Modules.Catalogo.Domain.Estoque", b =>
                {
                    b.HasOne("CommerceLab.Modules.Catalogo.Domain.Produto", null)
                        .WithOne()
                        .HasForeignKey("CommerceLab.Modules.Catalogo.Domain.Estoque", "ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_estoques_produtos_produto_id");
                });
#pragma warning restore 612, 618
        }
    }
}
